<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNKvTozi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNKvTozi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNKvTozi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNKvTozi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNKvTozi\App_KernelDevDebugContainer([
    'container.build_hash' => 'NKvTozi',
    'container.build_id' => 'cd71107e',
    'container.build_time' => 1746890604,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNKvTozi');
